### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/lightstones#1]
- [ ] Get permission from the dev to continue this
- [ ] Port ore gen to 1.18.2
- [ ] Port lava board to 1.18.2's model format
- [ ] Port rest of the mod to 1.18.2
- [ ] (MAYBE) [Lightstone Rifle](https://biosector01.com/wiki/Lightstone_Rifle)
